### ISSUE TITLE
GPUs memory leak

### ISSUE THREAD

**Issue by alibabadoufu** [Vision-CAIR/MiniGPT-4#11]
I was trying to serve the model in my local machine. However, when I increased the beam size, the GPU memory kept increasing and will reach the limit.

**Comment by nipunjindal** [comment]
Could you share your setup and which GPU were you able to make the inference on?

**Comment by TsuTikgiau** [comment]
Hello, when you increase the beam size, the model needs to generate more tokens and it will also cost more memory. In case you don't have GPU with large memories, suggest to use a small beam size

**Comment by TsuTikgiau** [comment]
@nipunjindal we update the default setting of the demo and now the demo should cost less than 24GB

**Comment by shen51000** [comment]
my GPU is only 8GB memory, can i run the demo locally?

**Comment by alibabadoufu** [comment]
> Hello, when you increase the beam size, the model needs to generate more tokens and it will also cost more memory. In case you don't have GPU with large memories, suggest to use a small beam size

Noted with thanks :D
