### ISSUE TITLE
Problems with "How to Prepare Vicuna Weight"

### ISSUE THREAD

**Issue by youdou24** [Vision-CAIR/MiniGPT-4#115]
when i run the commend 
python -m fastchat.model.apply_delta --base /Documents/workspace/llama-13b-hf/  --target /Documents/workspace/MiniGPT-4/vicuna_weight/  --delta /Documents/workspace/vicuna-13b-delta-v0/
![image](https://user-images.githubusercontent.com/26383109/233788391-6f97dea1-315a-46f4-8429-ec53bc9202fc.png)

is there something wrong with my  model of "llama-13b-hf"  ?

**Comment by youdou24** [comment]
i get my llama model from https://huggingface.co/decapoda-research/llama-13b-hf
would it be all right?

**Comment by youdou24** [comment]
its a OOM problem 
it can be resoved by add swapfile

**Comment by GITMrzk** [comment]
> its a OOM problem it can be resoved by add swapfile

could you please show a detailed solution?
