### ISSUE TITLE
RuntimeError: The size of tensor a (32000) must match the size of tensor b (32001) at non-singleton dimension 0

### ISSUE THREAD

**Issue by Coca-Cola1999** [Vision-CAIR/MiniGPT-4#132]
RuntimeError: The size of tensor a (32000) must match the size of tensor b (32001) at non-singleton dimension 0 after I execute this command：python -m fastchat.model.apply_delta --base llama-7b-hf/  --target vicuna-7b/  --delta vicuna-7b-delta-v0/

**Comment by ibisbill** [comment]
I encountered same problem. When param.data = 32000, this problem occurs. 
My solution is: expand para.data to 32001 using torch.cat only when the origin value equals 32000, then problem solved.

**Comment by Coca-Cola1999** [comment]
> torch.cat

Can you tell me which file to modify that line of code? I'm a newcomer

**Comment by ibisbill** [comment]
hi, 
the file is: fastchat/model/apply_delta.py
line:  137
hope this can help you!

**Comment by ibisbill** [comment]
You can try this 
`flagg = 0
    for name, param in tqdm(base.state_dict().items(), desc="Applying delta"):
        assert name in delta.state_dict()
        
        if flagg == 0 or flagg == 322:
            new_tensor = torch.zeros(1, 4096)
            param.data.size()
            param.data = torch.cat((param.data, new_tensor), dim=0)

        flagg += 1`

 before ` param.data += delta.state_dict()[name]`

**Comment by hfchensq1** [comment]
i encountered the same problem.do u mean by rewrite the apply_delta.py?

**Comment by hfchensq1** [comment]
> hi, the file is: fastchat/model/apply_delta.py line: 137, right before code `param.data += delta.state_dict()[name]` hope this can help you!

can u show the code please,I am not familiar with Python!I am afraid to change the code in package.

**Comment by Coca-Cola1999** [comment]
> hi, the file is: fastchat/model/apply_delta.py line: 137, right before code `param.data += delta.state_dict()[name]` hope this can help you!


> hi, the file is: fastchat/model/apply_delta.py line: 137, right before code `param.data += delta.state_dict()[name]` hope this can help you!

Thank u!Are you Chinese？Can we add a WeChat account？

**Comment by Coca-Cola1999** [comment]
> hi, the file is: fastchat/model/apply_delta.py line: 137, right before code `param.data += delta.state_dict()[name]` hope this can help you!

Thank u!Are you Chinese？Can we add a WeChat account？

**Comment by hfchensq1** [comment]
> > hi, the file is: fastchat/model/apply_delta.py line: 137, right before code `param.data += delta.state_dict()[name]` hope this can help you!
> 
> Thank u!Are you Chinese？Can we add a WeChat account？

你是国人嘛，这咋改那版代码，或者可以加微信沟通~

**Comment by Coca-Cola1999** [comment]
> > > hi, the file is: fastchat/model/apply_delta.py line: 137, right before code `param.data += delta.state_dict()[name]` hope this can help you!
> > 
> > 
> > Thank u!Are you Chinese？Can we add a WeChat account？
> 
> 你是国人嘛，这咋改那版代码，或者可以加微信沟通~

hhhh, 18622563703 微信加我吧

**Comment by hfchensq1** [comment]
> > > > hi, the file is: fastchat/model/apply_delta.py line: 137, right before code `param.data += delta.state_dict()[name]` hope this can help you!
> > > 
> > > 
> > > Thank u!Are you Chinese？Can we add a WeChat account？
> > 
> > 
> > 你是国人嘛，这咋改那版代码，或者可以加微信沟通~
> 
> hhhh, 18622563703 微信加我吧

加了~

**Comment by yPanStupidog** [comment]
Use version v1.1 rather than v0

**Comment by hfchensq1** [comment]
model version mismatch~

**Comment by jiajunhappyelements** [comment]
> > hi, the file is: fastchat/model/apply_delta.py line: 137, right before code `param.data += delta.state_dict()[name]` hope this can help you!
> 
> can u show the code please,I am not familiar with Python!I am afraid to change the code in package.

    print("Applying the delta")
    for name, param in tqdm(base.state_dict().items(), desc="Applying delta"):
        assert name in delta.state_dict()
        # param.data += delta.state_dict()[name]
        param.data = torch.cat((param.data, delta.state_dict()[name]), dim=0)

**Comment by ZyangLee** [comment]
> 

My setting is same as u, u can just low your fastchat version with the command ' pip install fschat==0.1.10', which can fix this issue. You can see 'FastChat version compatibility' docs in this site: [click this](https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md)

**Comment by ZyangLee** [comment]
> > 
> 
> My setting is same as u, u can just low your fastchat version with the command ' pip install fschat==0.1.10', which can fix this issue. You can see 'FastChat version compatibility' docs in this site: [click this](https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md)

My terminal command is like: 
python -m fastchat.model.apply_delta --base /home/yinhang/minigpt4/llama_hf_7b --target /home/yinhang/minigpt4/vicuna --delta /home/yinhang/minigpt4/vicuna-7b-delta-v0
And my fastchat==0.1.10
