### ISSUE TITLE
Running this project in a Docker container

### ISSUE THREAD

**Issue by 1605wzf** [Vision-CAIR/MiniGPT-4#135]
The gradio starts the project at **127.0.0.1 by default**; 
If you are using docker deployment ,the address must be set to **0.0.0.0.** 
Otherwise, address access errors will occur.
![image](https://user-images.githubusercontent.com/42125933/233917523-95554918-bfcf-4906-b2f2-a4e09d09bbdc.png)

**Comment by disarmyouwitha** [comment]
Thanks, this helped me.. you just need to edit the last line of demo.py to match the above
