### ISSUE TITLE
The procedure of downloading Llama

### ISSUE THREAD

**Issue by XiongweiWu** [Vision-CAIR/MiniGPT-4#149]
Hi, can u tell me the procedure of downloading the original weights of Llama-13b-hf? 

According to your instruction, I fill in the [form](https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform?usp=send_form) in [their website](https://huggingface.co/docs/transformers/main/model_doc/llama), however, they has not replied me for nearly one week. I find the original weight of Llama-13b from [this website](https://huggingface.co/huggyllama/llama-13b) and git pull the weights. 

However, when I tried to convert the Llama into hf as suggested in https://huggingface.co/docs/transformers/main/model_doc/llama , one error reports that 
`No such file or directory: 'llama-13b/13B/params.json'`

I am very new to this domain, and can u tell me the correct procedure to obtain the Llama-13b-hf?

**Comment by WeileiZeng** [comment]
use absolute path for the folder `/path/to/llama-13b/13B`

**Comment by XiongweiWu** [comment]
@WeileiZeng I know how to config the dataset, the question is how to download the original model and convert it into hugging face format, since I follow the official script but the error reports. However, I obtain the hf model from the third party repo.

**Comment by mijunhua** [comment]
> @WeileiZeng I know how to config the dataset, the question is how to download the original model and convert it into hugging face format, since I follow the official script but the error reports. However, I obtain the hf model from the third party repo.

Hi, I also encountered the same problem.
Could you please paste the download link of hf model?

**Comment by WeileiZeng** [comment]
llamA weights

magnet:?xt=urn:btih:ZXXDAUWYLRUXXBHUYEMS6Q5CE5WA3LVA&dn=LLaMA

**Comment by XiongweiWu** [comment]
> 

https://huggingface.co/decapoda-research/llama-13b-hf

**Comment by XiongweiWu** [comment]
> > @WeileiZeng I know how to config the dataset, the question is how to download the original model and convert it into hugging face format, since I follow the official script but the error reports. However, I obtain the hf model from the third party repo.
> 
> Hi, I also encountered the same problem. Could you please paste the download link of hf model?

https://huggingface.co/decapoda-research/llama-13b-hf
