### ISSUE TITLE
prepare weight failed: ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by loveJasmine** [Vision-CAIR/MiniGPT-4#155]
(minigpt4) ub2004@ub2004-B85M-A0:~/llm_dev/MiniGPT-4$ python -m fastchat.model.apply_delta --base /data1t/hf_model/llama-7b-hf/ --target ./workweight/  --delta /data1t/hf_model/vicuna-7b-delta-v0/
Loading the base model from /data1t/hf_model/llama-7b-hf/
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:29<00:00,  1.10it/s]
Loading the delta from /data1t/hf_model/vicuna-7b-delta-v0/
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:26<00:00, 13.28s/it]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ub2004/anaconda3/envs/minigpt4/lib/python3.9/runpy.py:197 in _run_module_as_main           │
│                                                                                                  │
│   194 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   195 │   if alter_argv:                                                                         │
│   196 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 197 │   return _run_code(code, main_globals, None,                                             │
│   198 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   199                                                                                            │
│   200 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ /home/ub2004/anaconda3/envs/minigpt4/lib/python3.9/runpy.py:87 in _run_code                      │
│                                                                                                  │
│    84 │   │   │   │   │      __loader__ = loader,                                                │
│    85 │   │   │   │   │      __package__ = pkg_name,                                             │
│    86 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  87 │   exec(code, run_globals)                                                                │
│    88 │   return run_globals                                                                     │
│    89                                                                                            │
│    90 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ /home/ub2004/anaconda3/envs/minigpt4/lib/python3.9/site-packages/fastchat/model/apply_delta.py:5 │
│ 1 in <module>                                                                                    │
│                                                                                                  │
│   48 │                                                                                           │
│   49 │   args = parser.parse_args()                                                              │
│   50 │                                                                                           │
│ ❱ 51 │   apply_delta(args.base_model_path, args.target_model_path, args.delta_path)              │
│   52                                                                                             │
│                                                                                                  │
│ /home/ub2004/anaconda3/envs/minigpt4/lib/python3.9/site-packages/fastchat/model/apply_delta.py:2 │
│ 4 in apply_delta                                                                                 │
│                                                                                                  │
│   21 │   delta_tokenizer = AutoTokenizer.from_pretrained(delta_path, use_fast=False)             │
│   22 │                                                                                           │
│   23 │   DEFAULT_PAD_TOKEN = "[PAD]"                                                             │
│ ❱ 24 │   base_tokenizer = AutoTokenizer.from_pretrained(base_model_path, use_fast=False)         │
│   25 │   num_new_tokens = base_tokenizer.add_special_tokens(dict(pad_token=DEFAULT_PAD_TOKEN)    │
│   26 │                                                                                           │
│   27 │   base.resize_token_embeddings(len(base_tokenizer))                                       │
│                                                                                                  │
│ /home/ub2004/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/models/auto/tokeni │
│ zation_auto.py:689 in from_pretrained                                                            │
│                                                                                                  │
│   686 │   │   │   │   tokenizer_class = tokenizer_class_from_name(tokenizer_class_candidate)     │
│   687 │   │   │                                                                                  │
│   688 │   │   │   if tokenizer_class is None:                                                    │
│ ❱ 689 │   │   │   │   raise ValueError(                                                          │
│   690 │   │   │   │   │   f"Tokenizer class {tokenizer_class_candidate} does not exist or is n   │
│   691 │   │   │   │   )                                                                          │
│   692 │   │   │   return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *input   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
(minigpt4) ub2004@ub2004-B85M-A0:~/llm_dev/MiniGPT-4$ 
(minigpt4) ub2004@ub2004-B85M-A0:~/llm_dev/MiniGPT-4$

**Comment by TsuTikgiau** [comment]
hello! you can check the solution here https://github.com/Vision-CAIR/MiniGPT-4/issues/59#issuecomment-1515129713

**Comment by loveJasmine** [comment]
it works
