### ISSUE TITLE
How to access the deployment on the server

### ISSUE THREAD

**Issue by whuxxie** [Vision-CAIR/MiniGPT-4#157]
The deployment on the server was successful, and it can be accessed on the server. However, using the server ip: port on the external network cannot be accessed. There is no problem with the firewall, and it is no problem to access the default port 80 of iis.

**Comment by quartets** [comment]
Hi, WeileiZeng!

can you tell me where do I put these parameters? Into which file?

Thanks

**Comment by WeileiZeng** [comment]
replace the last line in https://github.com/Vision-CAIR/MiniGPT-4/blob/main/demo.py

**Comment by whuxxie** [comment]
i tried，it worked
