### ISSUE TITLE
GPU Memory of A100

### ISSUE THREAD

**Issue by Unrealluver** [Vision-CAIR/MiniGPT-4#20]
Thanks for your excellent work! What's the GPU memory of your A100, 40G, or 80G? I have tried vicuna-13b on 8xA100(40G), but it will result in an OOM error.

**Comment by TsuTikgiau** [comment]
Thanks for your interest! We are using 80G. I'm not sure if you mean the training stage or the inference. In case you are talking about training, I think a simple way to avoid OOM is to use a smaller batch size. You can set it in the training config files under the folder train_config/. I think maybe 8bit vicuna can also reduce memory usage. But we haven't tested this in the training stage yet. In case you mean inference, the current inference is run on a single card and it doesn't support model parallel in multi GPU yet. So multiple GPU will not help the OOM issue. Some methods discussed in [this issue](https://github.com/Vision-CAIR/MiniGPT-4/issues/4#issue-1670562133) can reduce memory usage for inference dramatically. We are currently working on an official solution to make it run in a 24G memory GPU. Will return to you once it is finished

**Comment by XXXKAY** [comment]
> discussed

How much GPU memory do I need if I use it for inference?

**Comment by Unrealluver** [comment]
> Thanks for your interest! We are using 80G. I'm not sure if you mean the training stage or the inference. In case you are talking about training, I think a simple way to avoid OOM is to use a smaller batch size. You can set it in the training config files under the folder train_config/. I think maybe 8bit vicuna can also reduce memory usage. But we haven't tested this in the training stage yet. In case you mean inference, the current inference is run on a single card and it doesn't support model parallel in multi GPU yet. So multiple GPU will not help the OOM issue. Some methods discussed in [this issue](https://github.com/Vision-CAIR/MiniGPT-4/issues/4#issue-1670562133) can reduce memory usage for inference dramatically. We are currently working on an official solution to make it run in a 24G memory GPU. Will return to you once it is finished

Thanks for your reply. I use 8xA100(40G) for training Vicuna with a GPU OOM problem now.

**Comment by TsuTikgiau** [comment]
@XXXKAY We update the default hyperparameter for inference and load Vicuna as 8bit by default now when you launch the demo. Under this setting, the memory cost is about 23GB. You can check the updated readme for more information

**Comment by TsuTikgiau** [comment]
@Unrealluver In your case I think you can set the batchsize per GPU smaller in [minigpt4_stage1_pretrain.yaml](https://github.com/Vision-CAIR/MiniGPT-4/blob/main/train_configs/minigpt4_stage1_pretrain.yaml). The default is 64, which cost about 70+ GB per GPU
