### ISSUE TITLE
Can't get  LLAMA-7B or LLAMA-13B weights 

### ISSUE THREAD

**Issue by Tony363** [Vision-CAIR/MiniGPT-4#203]
Hello,

I filled the form from [huggingface](https://huggingface.co/docs/transformers/main/model_doc/llama) twice. I said I was doing undergraduate research for a college professor and used my college professors publications to fill the form. I have yet to hear back from Meta since 2 weeks ago.

How else can I procure the weights for LLAMA-7B or LLAMA-13B to setup MiniGPT-4?

Tony

**Comment by aries-ai-dev** [comment]
> 
I hope it can help you.

`git clone https://huggingface.co/decapoda-research/llama-13b-hf`

`git clone https://huggingface.co/decapoda-research/llama-7b-hf`

**Comment by wangfengjuan** [comment]
> > 
> 
> I hope it can help you.
> 
> `git clone https://huggingface.co/decapoda-research/llama-13b-hf`
> 
> `git clone https://huggingface.co/decapoda-research/llama-7b-hf`
Always show this：
fatal: 无法访问 'https://huggingface.co/decapoda-research/llama-13b-hf/'：Failed to connect to huggingface.co port 443: 连接超时
