### ISSUE TITLE
multi-gpu inference

### ISSUE THREAD

**Issue by R2D2-3PO** [Vision-CAIR/MiniGPT-4#236]
if i have like 2 16GB GPUs, how can I inference the 13B model?

**Comment by sushilkhadkaanon** [comment]
@R2D2-3PO How did you solve this?

**Comment by R2D2-3PO** [comment]
> @R2D2-3PO How did you solve this?

i can't

**Comment by 9cat** [comment]
is it possible to using  horovod?

https://github.com/horovod/horovod
