### ISSUE TITLE
[Feature Request]add use minigpt4 in google colab

### ISSUE THREAD

**Issue by WangRongsheng** [Vision-CAIR/MiniGPT-4#26]
Many people have difficulty using minigpt4, so can you provide a colab on how to use it?

**Comment by amrrs** [comment]
@WangRongsheng Did you find the colab somewhere?

**Comment by ChristianAchenbach4815** [comment]
Link is now in the documentation: [https://colab.research.google.com/drive/1OK4kYsZphwt5DXchKkzMBjYF6jnkqh4R?usp=sharing](https://colab.research.google.com/drive/1OK4kYsZphwt5DXchKkzMBjYF6jnkqh4R?usp=sharing)
