### ISSUE TITLE
run demo load checkpoint size mismatch

### ISSUE THREAD

**Issue by Zhudogsi** [Vision-CAIR/MiniGPT-4#269]
I encountered the following error while trying to run demo. How can I solve it? (Loaded with 7b)
RuntimeError: Error(s) in loading state_dict for MiniGPT4:
        size mismatch for llama_proj.weight: copying a param with shape torch.Size([4096, 768]) from checkpoint, the shape in current model is torch.Size([5120, 768]).
        size mismatch for llama_proj.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([5120]).

**Comment by Yimi81** [comment]
same here

**Comment by Yimi81** [comment]
Resolved, the reason is that the Vicuna version has not been changed to 7B
