### ISSUE TITLE
Strikethrough text (using a V100 graphics card)

### ISSUE THREAD

**Issue by Petilia** [Vision-CAIR/MiniGPT-4#27]
I am using a V100 graphics card (it does not support int8 operations, when I try to run low_resource=True there is an error with cuda_setup).

I put low_resource=False and run it, but I get crossed out and wrong text

I used the right weights (git-lfs clone https://huggingface.co/lmsys/vicuna-13b-delta-v0)
![image](https://user-images.githubusercontent.com/94632457/232712777-9fc398b9-2cd5-4cca-940e-060a5d8ae0d6.png)
![image](https://user-images.githubusercontent.com/94632457/232712972-d16879ed-a9b3-4f03-b680-164386c0628c.png)

**Comment by Andy1621** [comment]
I also met the same issue...

**Comment by stevezhang88** [comment]
https://huggingface.co/lmsys/vicuna-13b-delta-v0)  . I think this weight should be merged with LLaMa 13B weights.  Then works .

**Comment by TsuTikgiau** [comment]
Thanks for your interest in our work! People in this [issue](https://github.com/Vision-CAIR/MiniGPT-4/issues/12) show similar problems to your case, and their reason looks like they don't add the delta weight of vicuna back to llama weight to get the final working weight. Note that the vicuna weight you directly download is a delta version. And you need to follow their instruction to add this delta weight back to the original llama weight, to get the final working weight of vicuna. The reason why we need this complex process is that llama doesn't allow us to distribute their weights, so vicuna has to release a delta weight version to bypass this rule
