### ISSUE TITLE
How do you not calculate the regression loss for text-image prompt??

### ISSUE THREAD

**Issue by jacob-kang** [Vision-CAIR/MiniGPT-4#299]
Hi. thanks for your great works.

I read your paper. this is awesome and very helpful.

But I want to ask a question.
In your paper section **3.3 Second-stage finetuning** , the last sentence

> It is important to note that we do not calculate the regression loss for this specific text-image prompt.

In your code, You input the `###Human: <Img>` and `</Img> Please provide a detailed description of the picture. ###Assistant: ` 

When second-stage finetuning, Does back-propagation gradient flow into the sentence which you pre-defined prompt?

I think you probably consider the same one, and that's why you write the sentence.
> It is important to note that we do not calculate the regression loss for this specific text-image prompt.

If, yes, How do you ignore it? How do you not calculate the loss?

Thanks.

kind regards.

**Comment by jacob-kang** [comment]
I did by myself

**Comment by ericsua** [comment]
Hi @jacob-kang, I have the same questions, could you explain your findings? Thanks
