### ISSUE TITLE
Could I have the stage 1 checkpoint model?

### ISSUE THREAD

**Issue by chikiuso** [Vision-CAIR/MiniGPT-4#31]
Good morning, could I have the stage 1 checkpoint model? As I would like to fine tune the model on stage 2 with my own dataset, thanks for your help!

**Comment by franciszchen** [comment]
Same question. It would be beneficial to perform the stage 2 directly, without repeating the burdensome stage 1 for users.

**Comment by TsuTikgiau** [comment]
Hello! We uploaded the stage 1 checkpoint now. You can find it in the updated readme. Thanks!

**Comment by md-afif** [comment]
Hello, thanks releasing the stage 1 weights! Correct me if I am wrong, the uploaded stage 1 checkpoint is for a BLIP2 aligned with a vicuna-13b? Any chance you will be releasing the one with vicuna-7b?

**Comment by eduardofarina** [comment]
> Hello! We uploaded the stage 1 checkpoint now. You can find it in the updated readme. Thanks!
Hello, as mentioned by md-afif it would be super helpful if you could share the vicuna-7b stage 1 weights also.

**Comment by eduardofarina** [comment]
Hello, as mentioned by md-afif it would be super helpful if you could share the vicuna-7b stage 1 weights also.



> Hello! We uploaded the stage 1 checkpoint now. You can find it in the updated readme. Thanks!

**Comment by TsuTikgiau** [comment]
@md-afif @eduardofarina Hello! The stage 1 checkpoint for 7B model is now included in the updated readme
