### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in  directory  

### ISSUE THREAD

**Issue by dragen1860** [Vision-CAIR/MiniGPT-4#32]
Hi, all:
  I clone the repo and download the weights from https://huggingface.co/lmsys/vicuna-13b-delta-v0/tree/main, when run 
```
python demo.py --cfg-path eval_configs/minigpt4_eval.yaml
```
I encounter the following error: 
```
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in 
directory /media/sdb/xxx/LLama/vicuna_weights.
```

I double check the downloaded weights in /media/sdb/xxx/LLama/vicuna_weights:

![image](https://user-images.githubusercontent.com/4252555/232761453-4f691326-95d7-4006-a15c-9997c95c7ca7.png)

Anyone know what caused the OSError message? thanks.

**Comment by TsuTikgiau** [comment]
Thanks for your interest! The vicuna weight you downloaded is a delta version and need some further processing to turn it into a working version. Please refer to our updated readme to know how to prepare vicuna
