### ISSUE TITLE
What's the data license

### ISSUE THREAD

**Issue by viyjy** [Vision-CAIR/MiniGPT-4#327]
Hi, thanks for your great work.
I was wondering what's the license of your [second-stage dataset](https://drive.google.com/file/d/1nJXhoEcy3KTExr17I7BXqY5Y9Lx_-n-9/view)? Is that still BSD 3-Clause License? Can it be used for commercial use?

Thanks!!!

**Comment by TsuTikgiau** [comment]
Hello, the data is still BSD-3 Clause and you can use it for commercial use. Thank you!

**Comment by viyjy** [comment]
Thanks.
