### ISSUE TITLE
Trouble getting Vicuna weights

### ISSUE THREAD

**Issue by covalspace** [Vision-CAIR/MiniGPT-4#33]
I followed the links to get Vicuna weights but it appears as though I need to fill out a form to get the LLaMa weights and then apply the delta model on top of it?

Am I missing something? If not is there a faster way to get the Vicuna weights?

**Comment by covalspace** [comment]
I was missing something I just got weights from files section

**Comment by TsuTikgiau** [comment]
Hello @covalspace , the weights from their files sections are 'delta weight' but not the final working weight, you still need the original LLAMA weight, add the delta weight with original LLAMA weight together to get the final working weight. We now provide a guide in PrepareVicuna.md under the root folder to make it more clear.
