### ISSUE TITLE
Some question about finetuning ? 

### ISSUE THREAD

**Issue by 631068264** [Vision-CAIR/MiniGPT-4#341]
**Describe the bug**
After  read this https://github.com/Vision-CAIR/MiniGPT-4/blob/main/dataset/README_2_STAGE.md  , I have some question.

-  finetune model only use jpg ?  I have some png
- the dataset have the size limit？
- `caption` only accept English?  Can Chinese ?
- How to load finetune output model ?
- When I want to finetune for my personal data , just run stage 2?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TsuTikgiau** [comment]
Hello, thank you for your questions! 
1. for the data, both jpeg and png is fine
2. there is no limit for the dataset size. But usually the bigger the dataset is, the better result you will get
3. LLama works for both English and Chinese, so you can use Chinese data
4. the way to load a finetune model is the same as the way to load the provided pretrain model. Just specify the checkpoint path to the finetuned model checkpoint you saved.
5. finetune the model starting from stage 2 should be fine
