### ISSUE TITLE
Error llama2 llama_proj.weight size ([4096, 5632]) ?

### ISSUE THREAD

**Issue by ZeguanXiao** [Vision-CAIR/MiniGPT-4#350]
**Describe the bug**
```
pretrained_minigpt4 = torch.load("pretrained_minigpt4_llama2_7b_1.pth", map_location=torch.device('cpu'))["model"]
print(pretrained_minigpt4["llama_proj.weight"])
### torch.Size([4096, 5632]), which 5632 is not in llama2 config.
```

**Comment by saphtea** [comment]
How'd you fix this?

**Comment by ZeguanXiao** [comment]
This bug appeared when I implemented minigpt myself. The reason is that there are some differences between the implementation of the llama2 version and the vicuna version. If you encounter the same problem using this repository, you can check whether the configuration file is correct.
