### ISSUE TITLE
How to Training Own Dataset in Stage 1

### ISSUE THREAD

**Issue by AlanXU07** [Vision-CAIR/MiniGPT-4#354]
I want to training own dataset in stage 1 , in the minigpt4_stage1_pretrain.yaml file ,I comment out the   

    laion:
      vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
      text_processor:
         train:
           name: "blip_caption"
      sample_ratio: 115

    cc_sbu:
      vis_processor:
            train:
               name: "blip2_image_train"
               image_size: 224
       text_processor:
           train:
             name: "blip_caption"
        sample_ratio: 14
    
Because I just want to train my own dataset , and add my own data like
    
    parathyroid:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 115
    
I also added the file  /minigpt4/configs/datasets/parathyroid/defaults.yaml, my dataset folder have tsv file, json file and images.
    
And I run this command 
`torchrun --nproc-per-node 2(I use 2 V100) train.py --cfg-path train_configs/minigpt4_stage1_pretrain.yaml`
    
Then I got the error like
    Traceback (most recent call last):
  File "/root/M11117015thesis/MiniGPT-4/train.py", line 104, in <module>
    main()
  File "/root/M11117015thesis/MiniGPT-4/train.py", line 81, in main
    cfg = Config(parse_args())
  File "/root/M11117015thesis/MiniGPT-4/minigpt4/common/config.py", line 31, in __init__
    dataset_config = self.build_dataset_config(config)
  File "/root/M11117015thesis/MiniGPT-4/minigpt4/common/config.py", line 103, in build_dataset_config
    dataset_config_path = builder_cls.default_config_path(
AttributeError: 'NoneType' object has no attribute 'default_config_path'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 20825) of binary: /opt/conda/envs/minigpt4/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/minigpt4/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by AlanXU07** [comment]
I already debug the error by modifying several files, however I have the new problem.

```
[INFO] Start training
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.51s/it]
[INFO] dataset_ratios not specified, datasets will be concatenated (map-style datasets) or chained (webdataset.DataPipeline).
[INFO] Loaded 0 records for train split from the dataset.
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/webdataset/handlers.py:33: UserWarning: ValueError("didn't find ['json'] in ['__key__', '__url__', 'jpg']")
  warnings.warn(repr(exn))
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/webdataset/handlers.py:33: UserWarning: ValueError("didn't find ['json'] in ['__key__', '__url__', 'jpg']")
  warnings.warn(repr(exn))
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/webdataset/handlers.py:33: UserWarning: ValueError("didn't find ['json'] in ['__key__', '__url__', 'jpg']")
  warnings.warn(repr(exn))
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/webdataset/handlers.py:33: UserWarning: ValueError("didn't find ['json'] in ['__key__', '__url__', 'jpg']")
  warnings.warn(repr(exn))
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/webdataset/handlers.py:33: UserWarning: ValueError("didn't find ['json'] in ['__key__', '__url__', 'jpg']")
  warnings.warn(repr(exn))
module.llama_proj.weight
module.llama_proj.bias
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/webdataset/handlers.py:33: UserWarning: ValueError("didn't find ['json'] in ['__key__', '__url__', 'jpg']")
  warnings.warn(repr(exn))
[INFO] number of trainable parameters: 3149824
[INFO] Start training epoch 0, 5000 iters per inner epoch.
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/webdataset/handlers.py:33: UserWarning: ValueError("didn't find ['json'] in ['__key__', '__url__', 'jpg']")
  warnings.warn(repr(exn))
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/webdataset/handlers.py:33: UserWarning: ValueError("didn't find ['json'] in ['__key__', '__url__', 'jpg']")
  warnings.warn(repr(exn))
```

In \MiniGPT-4\minigpt4\datasets\datasets\cc_sbu_dataset.py this file ,I change the file into mydata.
But in these line

```
   self.inner_dataset = wds.DataPipeline(
       wds.ResampledShards(location),
       wds.tarfile_to_samples(handler=wds.warn_and_continue),
       wds.shuffle(1000, handler=wds.warn_and_continue),
       wds.decode("pilrgb", handler=wds.warn_and_continue),
       wds.to_tuple("jpg", "json", handler=wds.warn_and_continue),
       wds.map_tuple(self.vis_processor, handler=wds.warn_and_continue),
       wds.map(self.to_dict, handler=wds.warn_and_continue),
       )
```

my dataset already has jpg files and caption files,do I still need to do that ? How to skip?

my dataset structure

```
 │   ├── parathyroid
 │       ├── ReshapeImg.json
 │       ├── ReshapeImg.tsv
 │       └── images
 │           ├── 00000.tar
 │           ├── 0AA4387D81B25FDC55B744674EA1E935FB8FAB-img-00624-00010.jpg
 │           ...
```

**Comment by monjurulkarim** [comment]
@AlanXU07 Hello, What size is your custom dataset? I'm curious about its performance with smaller datasets.
