### ISSUE TITLE
Why is there no prompt for stage-1 training?

### ISSUE THREAD

**Issue by Veason-silverbullet** [Vision-CAIR/MiniGPT-4#359]
I must convey the greatest appreciation for this wonderful work.

May I know why there is no prompt for stage-1 training on the code? The paper says a prompt is used for stage-1 alignment as

`###Human: <Img><ImageFeature></Img> Describe this image in detail. Give as many details as
possible. Say everything you see. ###Assistant:`

Thanks in advance for this issue.

**Comment by TsuTikgiau** [comment]
In the first stage of training, we follow the practice of blip2's last stage, where no prompt is used. The prompt you show is used in a model after the stage 1 training to generate data for stage-2 training. This prompt is not used in the training. As you can see, the prompt asks the model to generate detailed descriptions, but we don't have detailed description data in the first stage. If we add this prompt in the first stage of training and still let the model to regress the short image captions in the dataset, the model can only generate short captions.

**Comment by Veason-silverbullet** [comment]
Understood. Many thanks for your explanation.
