### ISSUE TITLE
is there a new result for vqa?

### ISSUE THREAD

**Issue by Jar7** [Vision-CAIR/MiniGPT-4#366]
Hi~ Thank you for your work! 
Could I have some questions about the vqa, since it surprises me that it has such lower score compared with other models?
As I read your paper, the performance of this model on vqa is lower than blip2. I am wondering whether there is some latest data that proves it can achieve average performance (~78 in aokvqa) by some training strategy. 
Is the performance of blips2 (80.2 in aokvqa) in ablation A.2 trained by freezing or unfreezing qformer and vision encoder?

**Comment by TsuTikgiau** [comment]
The original MiniGPT4 is not designed/trained/optimized for traditional VQA tasks. Thus, the VQA scores are not high. The second version of MiniGPT4 with strong performance in traditional benchmarks will be released in a few days.
