### ISSUE TITLE
Mistake in the preparation of vicuna weights (error when loading delta weights)

### ISSUE THREAD

**Issue by Petilia** [Vision-CAIR/MiniGPT-4#37]
I run the script to get the vicuna weights and get the following error:

python3 -m fastchat.model.apply_delta \
    --base /home/docker_current/src/llama_weights/llama-13b \
    --target /home/docker_current/src/vicuna_weight \
    --delta /home/docker_current/src/vicuna-13b-delta-v0

![image](https://user-images.githubusercontent.com/94632457/232816066-ba535071-a560-4056-b1f7-6aa9513651a9.png)
![image](https://user-images.githubusercontent.com/94632457/232816334-4af946fe-00b4-4a9e-a7fc-d4c2d21c7a01.png)

**Comment by TsuTikgiau** [comment]
Thanks Petilia! I also met this error before. But it was gone when I just redownload the Vicuna weights. I think the downloading from vicuna delta weights might be not so stable. How do you download Vicuna weights? Do you use git clone or

**Comment by Petilia** [comment]
> Thanks for your interest! I also met this error before. But it was gone when I just redownload the Vicuna weights. I think the downloading from vicuna delta weights might be not so stable. How do you download Vicuna weights? Do you use git clone or

I use git-lfs clone

**Comment by TsuTikgiau** [comment]
Hello! The way you download looks ok. Can you maybe try to redownload the vicuna delta weight and try again?
