### ISSUE TITLE
[Feature request] MiniGPT-v2 train code

### ISSUE THREAD

**Issue by becauseofAI** [Vision-CAIR/MiniGPT-4#374]
Great work! 
When will you release the train code and steps of MiniGPT-v2?

**Comment by sdc17** [comment]
Wonderful work! Also looking forward to the evaluation code on downstream tasks!

**Comment by junchen14** [comment]
Thanks for your attention to our work. We will release the finetuning code in few days. Stay tuned!

**Comment by junchen14** [comment]
we have released the finetuning code of minigpt-v2
