### ISSUE TITLE
Non-existent version of transformers

### ISSUE THREAD

**Issue by Petilia** [Vision-CAIR/MiniGPT-4#38]
Suggested:
pip install git+https://github.com/huggingface/transformers@v0.1.10
However, no such version of transformers exists.

This version also conflicts with environment.yml

![image](https://user-images.githubusercontent.com/94632457/232820256-60fb462d-2418-41e7-8a36-c6c8a6384c72.png)
![image](https://user-images.githubusercontent.com/94632457/232820832-7f2f8576-58c7-4b64-ba17-840948b75b2e.png)

**Comment by TsuTikgiau** [comment]
Oh, thank you for point this out and sorry for this! The command is wrong and it should be
```
pip install git+https://github.com/lm-sys/FastChat.git@v0.1.10
```
We have updated the guide to fix it
