### ISSUE TITLE
What time release MiniGPT-v2 training code?

### ISSUE THREAD

**Issue by shengyuwoo** [Vision-CAIR/MiniGPT-4#380]
Hi, MiniGPT-v2 is also nice work.
we are looking forward to your release of the MiniGPT-v2 training code and related steps?

**Comment by junchen14** [comment]
Thanks for your attention to our work. We will release the finetuning code in few days. Stay tuned!

**Comment by dirtycomputer** [comment]
looking forward

**Comment by shisantaibao** [comment]
Is the fine -tuning data set format of minigpt and V2 version the same? Or do you use a new format data set?

**Comment by junchen14** [comment]
the finetuning code for v2 will be released soon! the finetuning data format is a bit different between the first and second version

**Comment by dirtycomputer** [comment]
Will the training/fine-tuning code for GPT-2 be released before the CVPR 2024 paper submission deadline(18 days later)?

**Comment by junchen14** [comment]
we have released the finetuning code of minigpt-v2
