### ISSUE TITLE
Why does Q-former still need to load from FLAN-T5XXL when running the stage2?

### ISSUE THREAD

**Issue by becauseofAI** [Vision-CAIR/MiniGPT-4#384]
I did not run stage1 for pretraining, but instead used the [pretrained weights (7B)](https://drive.google.com/file/d/1HihQtCEXUyBM1i9DQbaK934wW3TZi-h5/view?usp=share_link) of stage1 to run stage2.
When I run stage2 to finetune MiniGPT4 with the following command:
```torchrun --nproc-per-node 1 train.py --cfg-path train_configs/minigpt4_stage2_finetune.yaml```
Why does the program need to download the Flant5xxl model when loading Q-former? As shown in the following figure.
![image](https://github.com/Vision-CAIR/MiniGPT-4/assets/31701434/afba03ed-f653-4eaf-86b7-956d9d47840c)

According to my naive understanding, Q-former should already be included in the weights of the stage1 pretraining, so just load the weights of the stage1 directly, right?

Bye the way, I had set the local path of `llama_model` in [minigpt4/configs/models/minigpt4_vicuna0.yaml](minigpt4/configs/models/minigpt4_vicuna0.yaml#L18) at Line 8 with [Vicuna V0 7B](https://huggingface.co/Vision-CAIR/vicuna-7b/tree/main) and `ckpt` in  [train_configs/minigpt4_stage2_finetune.yaml](train_configs/minigpt4_stage2_finetune.yaml#L9) at Line 9 with [pretrained weights (7B)](https://drive.google.com/file/d/1HihQtCEXUyBM1i9DQbaK934wW3TZi-h5/view?usp=share_link).

**Comment by TsuTikgiau** [comment]
For MiniGPT-4, both stage 1 and 2 doesn't finetune Q-former. So the checkpoint from the stage1 doesn't contain Q-former's weights

**Comment by becauseofAI** [comment]
> For MiniGPT-4, both stage 1 and 2 doesn't finetune Q-former. So the checkpoint from the stage1 doesn't contain Q-former's weights

I got it. Thx!

**Comment by qwqwq1445** [comment]
I wonder why don't you load the weights of BLIP2_pretrained_vicuna7b.pth?
