### ISSUE TITLE
How to deal with special tokens in MiniGPT-v2 

### ISSUE THREAD

**Issue by hmxiong** [Vision-CAIR/MiniGPT-4#388]
Great work！ I have a question about the special tokens and location tokens mentioned in the MiniGPT-v2 paper. Does the model need to expand the original vocabulary when building these tokens, or are these special tokens still based on the original LLaMA vocabulary? If these tokens are newly added, how to deal with the embedding layer and head in the original LLaMA during training?
![image](https://github.com/Vision-CAIR/MiniGPT-4/assets/74129781/844d4db3-a922-4eec-bed0-8fc008012a38)

**Comment by junchen14** [comment]
Thanks for your interest in our work.
Those tokens are based on original LLaMA 2 vocabulary

**Comment by junchen14** [comment]
you can check those special tokens from the files in minigpt4/datasets/datasets
