### ISSUE TITLE
Confusing performance in the web demo

### ISSUE THREAD

**Issue by Li-Jinsong** [Vision-CAIR/MiniGPT-4#408]
It feels like the model is talking nonsense.

- When use the "MiniGPT-v2 (online developing demo)" checkpoint:
![image](https://github.com/Vision-CAIR/MiniGPT-4/assets/106020747/d2b981a4-f9ef-4a54-a2d2-09974339c5c8)

- When use the "MiniGPT-v2 (after stage-3)" checkpoint:
![image](https://github.com/Vision-CAIR/MiniGPT-4/assets/106020747/6ea6b2b5-fc1b-46e6-814c-7c465f726677)

**Comment by TsuTikgiau** [comment]
Hello! Which peft version you are using? Some people report that if the peft is not 0.2.0, the generation is not correct. See [this issue](https://github.com/Vision-CAIR/MiniGPT-4/issues/381)

**Comment by Li-Jinsong** [comment]
> Hello! Which peft version you are using? Some people report that if the peft is not 0.2.0, the generation is not correct. See [this issue](https://github.com/Vision-CAIR/MiniGPT-4/issues/381)

Thanks, it solved the issue.
