### ISSUE TITLE
Finetune on multiple images caption task.

### ISSUE THREAD

**Issue by jiarenyf** [Vision-CAIR/MiniGPT-4#411]
I want to finetune the model on multiple images caption task.

Can I just change the output of the dataset: return {"image": images, "answer": captionx, "instruction_input": instruct} ?

To support multiple image ?

**Comment by jiarenyf** [comment]
Seems ok ...

**Comment by Abhiram4572** [comment]
Could you please enlighten us about the solution for the same?
