### ISSUE TITLE
Is there a  bug in refcoco dataset during training

### ISSUE THREAD

**Issue by LKJacky** [Vision-CAIR/MiniGPT-4#414]
**Describe the bug**

I think there may be a bug for refcoco datasets. In the minigpt4v2 [config](https://github.com/Vision-CAIR/MiniGPT-4/blob/23671f986135de7947117e0e1a514eeb6b67bea2/train_configs/minigptv2_finetune.yaml#L143C17-L143C17), 
blip2_image_train vision prossesor uses RandomResizedCrop to augment images, but the bboxes are not transformed equivalently in [dataset code](https://github.com/Vision-CAIR/MiniGPT-4/blob/23671f986135de7947117e0e1a514eeb6b67bea2/minigpt4/datasets/datasets/coco_dataset.py#L67).

Therefore, the bbox coordinates do not match the augmented images.

**Comment by junchen14** [comment]
Thanks for pointing this out. The reason is that we did not correctly merge this part into the main repo. It has been updated now!
