### ISSUE TITLE
minigpt-v2 inference result not correct

### ISSUE THREAD

**Issue by northeastsquare** [Vision-CAIR/MiniGPT-4#415]
python demo_v2.py --cfg-path eval_configs/minigptv2_eval.yaml  --gpu-id 0

<img width="1277" alt="image" src="https://github.com/Vision-CAIR/MiniGPT-4/assets/3086078/fc07ad69-b47f-49f0-86a5-92acb6449072">

<img width="493" alt="image" src="https://github.com/Vision-CAIR/MiniGPT-4/assets/3086078/5d8cdf71-98af-40a2-903a-7c01d943aef6">

<img width="466" alt="image" src="https://github.com/Vision-CAIR/MiniGPT-4/assets/3086078/908a844c-ce6c-43a4-bd5e-30ed8902a034">

**Comment by junchen14** [comment]
have you installed the correct peft version? it should be version 0.2.0

**Comment by lckj2009** [comment]
> have you installed the correct peft version? it should be version 0.2.0

Hello, with the latest version of Vision CAIR/MiniGPT-4, whether you are using Minipt4_ Eval. yaml, minigpt4_ Llama2_ Eval. yaml, minigptv2_ Eval. yaml can cause errors for the building owner. How can I solve them?

**Comment by lckj2009** [comment]
> have you installed the correct peft version? it should be version 0.2.0

Also, can I communicate in Chinese？

**Comment by lckj2009** [comment]
> have you installed the correct peft version? it should be version 0.2.0

Yes, I also encountered the same mistake. I installed version peft=0.2.0。May I ask how to solve this problem？？

**Comment by northeastsquare** [comment]
问题解决了。是语言模型，下载的不对

**Comment by lckj2009** [comment]
> 问题解决了。是语言模型，下载的不对

请问要下载什么模型呢？
