### ISSUE TITLE
How to reproduce the results using the same prompt?

### ISSUE THREAD

**Issue by becauseofAI** [Vision-CAIR/MiniGPT-4#418]
How to reproduce the results using the same prompt?

**Comment by junchen14** [comment]
You can just use our provided default prompt and script, and perform the evaluation with our updated after-stage3 checkpoint. You can reproduce the results in the paper

**Comment by becauseofAI** [comment]
I mean, during demo testing, the same prompt will produce different results each time it is run. Can we control the same prompt to produce the same or as similar results as possible? @junchen14

**Comment by junchen14** [comment]
you need to set the do_sample=False in [here](https://github.com/Vision-CAIR/MiniGPT-4/blob/68d81af31cc9237032e32e44947c5e04eb52b121/minigpt4/conversation/conversation.py#L176) to enable the same output each time
