### ISSUE TITLE
strikethrough character on gradio web app

### ISSUE THREAD

**Issue by steppige** [Vision-CAIR/MiniGPT-4#42]
The webapp works great and I don't get any errors in working, but I stick to responses with strikethrough character. Does anyone know why?

Thank you and congratulations for the project!!
<img width="1364" alt="Screenshot 2023-04-19 alle 00 02 27" src="https://user-images.githubusercontent.com/22180443/232916235-ea929bdd-8b8e-4a2d-b7f3-dcfae77b70c9.png">

**Comment by TsuTikgiau** [comment]
The code is updated to remove the first start token <s>
