### ISSUE TITLE
Clarification on Flickr30K Entities Dataset Usage

### ISSUE THREAD

**Issue by MajorDavidZhang** [Vision-CAIR/MiniGPT-4#421]
Hi,

Firstly, I'd like to express my appreciation for the remarkable work you've done with MiniGPT-v2. I am currently conducting an evaluation that involves your model, and I need some clarification regarding the dataset used during the training phase.

Could you please confirm whether the test and validation splits of the Flickr30K Entities dataset were included in your training process? The paper does not explicitly mention whether the entire Flickr30k Entities dataset was utilized or if only the training split was used.

This information is crucial for my evaluation work, and I would greatly appreciate your prompt response.

Thank you.

**Comment by xiaoqian-shen** [comment]
Thanks for your concern. We only use the official train split in the training process.
