### ISSUE TITLE
Where to find refcoco_val.json

### ISSUE THREAD

**Issue by LKJacky** [Vision-CAIR/MiniGPT-4#459]
I want to eval the model on refcoco. I follow the readme and prepare the datasets, However the code eval_ref.py needs a file named refcoco_val.json, which is not mentioned in readme.

So, I wonder where to find refcoco_val.json.

**Comment by conheaven** [comment]
how you solve this ?
thx

**Comment by p81sunshine** [comment]
how you solve this ?
thx

**Comment by LKJacky** [comment]
The author put data in [folder](https://github.com/Vision-CAIR/MiniGPT-4/tree/71df7647b664e20f6e209e75dc8189105e6950e2/eval_scripts/eval_data)
