### ISSUE TITLE
throws the StopIteration error

### ISSUE THREAD

**Issue by 1429904852** [Vision-CAIR/MiniGPT-4#467]
When I fine-tune the checkpoint_stage2.pth model using minigptv2_finetune.yaml script, the program throws the StopIteration error (I set the batch_size=1 for all datasets), The specific log is as follows:

<img width="914" alt="image" src="https://github.com/Vision-CAIR/MiniGPT-4/assets/34151761/96f9778d-a13e-4cb4-aa74-d620a64ca625">

<img width="890" alt="image" src="https://github.com/Vision-CAIR/MiniGPT-4/assets/34151761/4b549b6b-1bf2-41af-bb02-aa5985e0a2ec">

<img width="891" alt="image" src="https://github.com/Vision-CAIR/MiniGPT-4/assets/34151761/f38a5497-d5b6-44e7-887a-44f8a18e0a04">

<img width="955" alt="image" src="https://github.com/Vision-CAIR/MiniGPT-4/assets/34151761/ba1849dc-ffcc-4eea-9f35-1c41adaded5d">

​

**Comment by Hemanth-Kumar-K** [comment]
We are also facing the same issue can you guys help us in rectifying the issue

**Comment by RonaldYuren** [comment]
> We are also facing the same issue can you guys help us in rectifying the issue

Hi  I am encounter the same Error with my custom dataset and using checkpoint from stage3, Does this problem already fixed?
