### ISSUE TITLE
Correct work, but crossed out text

### ISSUE THREAD

**Issue by Petilia** [Vision-CAIR/MiniGPT-4#47]
Started the model, answers image questions correctly, but the text is crossed out for some reason
![image](https://user-images.githubusercontent.com/94632457/233017037-f1cb320f-6a4f-449a-ab99-4d45ae4087ab.png)

**Comment by TsuTikgiau** [comment]
Hello! We just updated the code to fix this issue. Can you pull the code and have a test again?
