### ISSUE TITLE
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

### ISSUE THREAD

**Issue by ensthee** [Vision-CAIR/MiniGPT-4#471]
**Describe the bug**
When I try to run demo.py, it come across that the local port can run in  http://127.0.0.1:7861,but can not create the share link.

**To Reproduce**
python3 demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0Initializing Chat

**Expected behavior**
It should output the share link

**Screenshots**
login to server failed: EOF

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

**Desktop (please complete the following information):**
Package                   Version
------------------------- ------------
accelerate                0.20.3
aiofiles                  23.2.1
aiohttp                   3.9.1
aiosignal                 1.3.1
altair                    5.2.0
annotated-types           0.6.0
antlr4-python3-runtime    4.9.3
anyio                     4.2.0
appdirs                   1.4.4
async-timeout             4.0.3
attrs                     23.1.0
beautifulsoup4            4.12.2
bitsandbytes              0.41.3.post2
braceexpand               0.1.7
certifi                   2023.11.17
charset-normalizer        3.3.2
click                     8.1.7
cmake                     3.28.1
colorama                  0.4.6
contourpy                 1.2.0
cycler                    0.12.1
decord                    0.6.0
docker-pycreds            0.4.0
exceptiongroup            1.2.0
fastapi                   0.108.0
ffmpy                     0.3.1
filelock                  3.13.1
fonttools                 4.47.0
frozenlist                1.4.1
fsspec                    2023.12.2
gdown                     4.7.1
gitdb                     4.0.11
GitPython                 3.1.40
gradio                    3.47.1
gradio_client             0.6.0
h11                       0.14.0
hf_transfer               0.1.4
httpcore                  1.0.2
httpx                     0.26.0
huggingface-hub           0.18.0
idna                      3.6
imageio                   2.33.1
importlib-resources       6.1.1
iopath                    0.1.10
Jinja2                    3.1.2
joblib                    1.3.2
jsonschema                4.20.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
lazy_loader               0.3
linkify-it-py             2.0.2
lit                       17.0.6
markdown-it-py            2.2.0
MarkupSafe                2.1.3
matplotlib                3.7.0
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.4
networkx                  3.2.1
nltk                      3.8.1
numpy                     1.26.2
nvidia-cublas-cu11        11.10.3.66
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cudnn-cu11         8.5.0.96
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.2.10.91
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusparse-cu11      11.7.4.91
nvidia-nccl-cu11          2.14.3
nvidia-nvtx-cu11          11.7.91
omegaconf                 2.3.0
opencv-python             4.7.0.72
orjson                    3.9.10
packaging                 23.2
pandas                    2.1.4
peft                      0.2.0
Pillow                    10.1.0
pip                       23.3.1
portalocker               2.8.2
progressbar2              4.3.2
protobuf                  4.25.1
psutil                    5.9.4
pydantic                  2.5.3
pydantic_core             2.14.6
pydub                     0.25.1
Pygments                  2.17.2
pyparsing                 3.1.1
PySocks                   1.7.1
python-dateutil           2.8.2
python-multipart          0.0.6
python-utils              3.8.1
pytz                      2023.3.post1
PyYAML                    6.0
referencing               0.32.0
regex                     2022.10.31
requests                  2.31.0
rich                      13.7.0
rpds-py                   0.16.2
safetensors               0.4.1
scikit-image              0.22.0
scikit-learn              1.3.2
scipy                     1.11.4
semantic-version          2.10.0
sentence-transformers     2.2.2
sentencepiece             0.1.99
sentry-sdk                1.39.1
setproctitle              1.3.3
setuptools                68.2.2
shellingham               1.5.4
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
soupsieve                 2.5
starlette                 0.32.0.post1
sympy                     1.12
threadpoolctl             3.2.0
tifffile                  2023.12.9
timm                      0.6.13
tokenizers                0.13.2
tomlkit                   0.12.0
toolz                     0.12.0
torch                     2.0.0
torchaudio                2.0.1
torchvision               0.15.1
tqdm                      4.64.1
transformers              4.30.0
triton                    2.0.0
typer                     0.9.0
typing_extensions         4.9.0
tzdata                    2023.3
uc-micro-py               1.0.2
urllib3                   2.1.0
uvicorn                   0.25.0
visual-genome             1.1.1
wandb                     0.16.1
webdataset                0.2.48
websockets                11.0.3
wheel                     0.41.2
yarl                      1.9.4
zipp                      3.17.0
**Smartphone (please complete the following information):*

**Additional context**

**Comment by ensthee** [comment]
OK,I have already sloved it,if you are in China,remember to turn you proxy on

**Comment by yutis-naucheryn** [comment]
> OK,I have already sloved it,if you are in China,remember to turn you proxy on

May I inquire about how you resolved the issue? I have encountered a similar problem but am unsure of how to address it.

**Comment by zhenhua22** [comment]
but, when i turn on it , it still roport me
