### ISSUE TITLE
zero-shot image inference is not working

### ISSUE THREAD

**Issue by SangbumChoi** [Vision-CAIR/MiniGPT-4#65]
<img width="1572" alt="스크린샷 2023-04-20 오후 1 15 16" src="https://user-images.githubusercontent.com/34004152/233256677-86a113ef-67b7-4825-9dc0-aedeca2c029f.png">

Does this expected behavior? since this project was aimed for specific target dataset

**Comment by SangbumChoi** [comment]
https://github.com/Vision-CAIR/MiniGPT-4/issues/48 Still have this error with modification btw

**Comment by SangbumChoi** [comment]
Sorry my bad. This was the reason of not merging delta and original weight of vicuna model

**Comment by MrWhiteHomeman** [comment]
I meet the same problem , how can i fix it , can you help me ?

**Comment by SangbumChoi** [comment]
@MrWhiteHomeman My issue was mentioned above, soley using delta file of vicuna model will cause above error. Try to merge original weight.
