### ISSUE TITLE
I made a colab I hope you like it 

### ISSUE THREAD

**Issue by camenduru** [Vision-CAIR/MiniGPT-4#76]
thanks for the project ❤ 

https://github.com/camenduru/MiniGPT-4-colab

**Comment by xiaoqian-shen** [comment]
Thank you! We'll incorporate your Colab guide.

**Comment by WangRongsheng** [comment]
You must use google colab pro to run it! It so bad!

**Comment by WangRongsheng** [comment]
#81 maybe it is better.
