### ISSUE TITLE
donate a new public demo

### ISSUE THREAD

**Issue by youkaichao** [Vision-CAIR/MiniGPT-4#91]
Hi, I see that the public demo at huggingface spaces is very crowded. Here I have built another public demo website at https://ws-4e7ab832-7a9c-4162-984a-f6b39dafc615-debug.rde-ws.vke-bj.lanrui-ai.com . Do you want to add this to the readme so that more people can try this out?

Thanks for the wonderful project!

**Comment by Korner83** [comment]
For me it gives an error after uploading the image.

**Comment by youkaichao** [comment]
@Korner83 thanks for your interest. I have restarted the demo and it should work now. It seems to be some bug caused by the project code.

**Comment by kenneth104** [comment]
wooooo, thank you  :D

**Comment by bigbrother001** [comment]
While, it is 404 not found now.
